M48
; DRILL file {KiCad 9.0.5} date 2025-11-18T22:54:16+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-18T22:54:16+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X147.385Y-71.9
X152.235Y-71.9
T2
X147.085Y-68.87
X152.535Y-68.87
M30
